language: python
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y maven2 python3-pip
script:
  - curl http://trec-car.cs.unh.edu/datareleases/v1.5/test200-v1.5.tar.xz | tar -xJ

  - pip3 install --user python3/
  - python3/test.py pages test200/train.test200.cbor >/dev/null
  - python3/test.py paragraphs test200/train.test200.cbor.paragraphs >/dev/null

  - cd trec-car-tools-example/
  - mvn install
  - mvn org.codehaus.mojo:exec-maven-plugin:1.5.0:java -Dexec.mainClass="edu.unh.cs.treccar_v2.read_data.ReadDataTest"  -Dexec.args="pages ../test200/train.test200.cbor" >/dev/null
  - mvn org.codehaus.mojo:exec-maven-plugin:1.5.0:java -Dexec.mainClass="edu.unh.cs.treccar_v2.read_data.ReadDataTest"  -Dexec.args="paragraphs ../test200/train.test200.cbor.paragraphs" >/dev/null
