language: python
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y maven2 python3-pip
script:
  - curl http://trec-car.cs.unh.edu/datareleases/v1.5/test200-v1.5.tar.xz | tar -xJ

  - pip3 install --user python3/
  - python3/test.py pages test200/train.test200.cbor >/dev/null
  - python3/test.py paragraphs test200/train.test200.cbor.paragraphs >/dev/null
